from __future__ import annotations

import sys
import unittest
from pathlib import Path

PLUGIN_ROOT = Path(__file__).resolve().parents[1]
if str(PLUGIN_ROOT) not in sys.path:
    sys.path.insert(0, str(PLUGIN_ROOT))

from libraries.attribution import attribution_text  # noqa: E402
from libraries.maimaidx_alias_sync import (  # noqa: E402
    fetch_yuzu_aliases,
    normalize_yuzu_alias_payload,
    yuzu_alias_urls,
)


class AliasSyncTests(unittest.TestCase):
    def test_normalizes_current_and_legacy_yuzu_payloads(self):
        self.assertEqual(
            normalize_yuzu_alias_payload(
                [{"song_id": 11394, "alias": ["寡", "寡", "寡王"]}]
            ),
            {"11394": ["寡", "寡王"]},
        )
        self.assertEqual(
            normalize_yuzu_alias_payload(
                {"content": [{"SongID": 11848, "Alias": ["ojod"]}]}
            ),
            {"11848": ["ojod"]},
        )
        self.assertEqual(
            normalize_yuzu_alias_payload({"11848": ["ojod", "OJOD"]}),
            {"11848": ["ojod"]},
        )

    def test_duplicate_rows_are_merged(self):
        self.assertEqual(
            normalize_yuzu_alias_payload(
                [
                    {"song_id": 833, "alias": ["第一"]},
                    {"song_id": 833, "alias": ["第二", "第一"]},
                ]
            ),
            {"833": ["第一", "第二"]},
        )

    def test_proxy_endpoint_is_selectable(self):
        self.assertIn("www.yuzuchan.cn", yuzu_alias_urls(proxy=True)[0])
        self.assertIn("www.yuzuchan.moe", yuzu_alias_urls(proxy=False)[0])

    def test_fetch_uses_mocked_public_response(self):
        class Response:
            status_code = 200

            @staticmethod
            def json():
                return [{"song_id": 833, "alias": ["测试别名"]}]

        class Client:
            def __init__(self):
                self.urls = []

            async def get(self, url):
                self.urls.append(url)
                return Response()

        async def run():
            client = Client()
            aliases = await fetch_yuzu_aliases(client)
            self.assertEqual(aliases, {"833": ["测试别名"]})
            self.assertEqual(client.urls, [yuzu_alias_urls()[0]])

        import asyncio

        asyncio.run(run())

    def test_derived_image_credit_has_no_bot_suffix(self):
        text = attribution_text("lxns")
        self.assertNotIn("Generated by", text)
        self.assertNotIn("MizukiBot", text)
        self.assertEqual(
            text,
            "Designed by Yuri-YuzuChaN & BlueDeer233. "
            "Adapted by Amia_晓山瑞希. Data from LXNS.",
        )
        self.assertTrue(attribution_text("merged").endswith("Data from LXNS & Diving-Fish."))


if __name__ == "__main__":
    unittest.main()
